[package]
name = "chopper"
version = "0.0.1"
authors = ["Xinyun Wu <xin@snaar.net>"]
edition = "2018"
repository = "https://github.com/snaar/chopper"

[dependencies]
byteorder = "1"
chrono = "0.4"
clap = "2"
csv = "1"
dtoa = "0.4"
flate2 = "1"
lazy_static = "1"
lzf = "0.3"
reqwest = "0.9"
backtrace = "0.3"

[lib]
name = "chopper_lib"
path = "src/lib.rs"

[[bin]]
name = "chop"
path = "src/main.rs"
